spring.application.name=insurance
spring.datasource.url=jdbc:mysql://localhost:3306/InsuranceSystem
spring.datasource.username=root
spring.datasource.password=will add later
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true